[project]
name = "secops-mcp-server"
version = "0.1.0"
description = "GitGuardian MCP server for SecOps with comprehensive security tools"
authors = [
    { name = "GitGuardian", email = "support@gitguardian.com" },
]
maintainers = [
    {name = "GitGuardian", email = "support@gitguardian.com"},
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: System Administrators",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Environment :: Console",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Topic :: Security",
]
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
dependencies = [
    "fastmcp~=3.0",
    "httpx~=0.28",
    "pydantic~=2.12",
    "gg-api-core",
    "uvicorn~=0.34",
    "gunicorn~=23.0"
]

[project.optional-dependencies]
sentry = [
    "gg-api-core[sentry]",
]

[project.scripts]
secops-mcp-server = "secops_mcp_server.run:run_mcp_server"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"